name: Build Native C++ Project

on:
  push:
  workflow_dispatch:

jobs:
  build-native:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 3.30.3

      - name: Create build directory
        run: mkdir build

      - name: Configure with CMake
        run: cmake ..
        working-directory: build

      - name: Build
        run: cmake --build .
        working-directory: build
